<?php
$z[0]=Array("spaceurl","",85,103);
$z[1]=Array("face","",132,145);
$z[2]=Array("spaceurl","",192,210);
$z[3]=Array("uname","",229,243);
$z[4]=Array("spaceurl","",293,311);
$z[5]=Array("spaceurl","",383,401);
$z[6]=Array("spaceurl","",468,486);
$z[7]=Array("rankname","",607,625);
$z[8]=Array("jointime","",689,741);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",805,858);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>