<?php
$z[0]=Array("specnote","\r\n                <li><span class=\"date\">[field:typename/]</span><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n                ",0,391);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="";
$z[0][4]['name']="默认节点";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="10";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>