<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,541);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",671,696);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("include","",764,799);
$z[7][4]['filename']="head.htm";
$z[8]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1014,1156);
$z[8][4]['row']="60";
$z[8][4]['sort']="new";
$z[9]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1304,1448);
$z[9][4]['row']="60";
$z[9][4]['sort']="month";
$z[10]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1592,1736);
$z[10][4]['row']="100";
$z[10][4]['sort']="rand";
$z[11]=Array("include","",1779,1816);
$z[11][4]['filename']="footer.htm";

?>